name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: datestamp
        run: sed -i "s/__DATE__/${DATE}/g" cv.tex
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: cv.tex
