name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: datestamp
        run: sed -i "s/__DATE__/${DATE}/g" cv.tex
      - name: Compile LaTeX document
        uses: docker://zibby/latex
        with:
         args: make
